<!DOCTYPE html>
<html>
<head>
	<header>
<center><img src="pp.png" width="100" height="100"></center>


<font color="#FFFFFF"><center><h2><strong>BIODATA</strong></h2><center>
	<h3><em><h5 align="center"> perkenalkan saya...</h5></em><h3>
	</font>
</header>
<style>
	header{
		background-color: black;
	}
</style>
<center><details>
<summary>kepo? KLIK aja</summary>
<h3><p> Nama saya ahmad fajri nasrulloh,Saya dari bandung dan sekarang saya tinggal di tanjungsari kabupaten sumedang </p></h3>

           <h4><p><em>Everyone thinks of changing the world, but no one thinks of changing himself.
    You can either experience the pain of discipline or the pain of regret. The choice is yours
Words can inspire, thoughts can provoke, but only action truly brings you closer to your dreams</p></em>
<p>-believe in yourself-</p>
</details></center></h4>
<p></p>
<p></p>
<center>
	<p>
	<img src="ig.png" height="30" width="30"><a href="https://www.instagram.com/afaj_rii/">@afaj_rii</a>

	<img src="x.png" height="30" width="40"> <a href="https://twitter.com/?lang=id">@Jriii</a> 

	<img src="fb.png" height="30" width="30";><a href="https://www.facebook.com/?locale=id_ID">@afajribangor</a> 
	<img src="wa.png" height="40" width="40"><a href="https://web.whatsapp.com/">+6289562205453</a>
</p>
</center>
</p>	
<p><center><strong>
	thankss, enjoyy, and have a nice dayy ><
</p></center></strong>
